FROM python:3.7

LABEL maintainer="jackleeforce@gmail.com"

WORKDIR /mobile_capture_server


RUN pip install pipenv -i https://pypi.douban.com/simple/ --trusted-host pypi.douban.com 


CMD ["sh", "run.sh"]


